---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ $.Values.accountID }}:role/{{ $.Values.clusterName }}-app-role-{{ $.Values.environmentInternalName }}
    privatecloud.mendix.com/environment-account: "true"
  name: {{ $.Values.environmentInternalName }}
  namespace: {{ $.Values.namespace }}